---
version: 2.1

executors:
  python:
    docker:
    - image: circleci/python:latest
  golang:
    docker:
    - image: circleci/golang:1.13

jobs:
  build:
    executor: golang
    steps:
    - run: go get -u github.com/prometheus/client_golang/examples/random
    - run: ls -l /go/bin/random
    - persist_to_workspace:
        root: /
        paths:
        - go/bin

  mixins:
    executor: golang
    steps:
    - run: go get -u github.com/google/go-jsonnet/cmd/jsonnet
    - run: go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
    - run: |
        git clone --depth 1 --no-checkout --filter=blob:none https://github.com/prometheus/prometheus.git prometheus
        cd prometheus
        git checkout master -- documentation/prometheus-mixin
    - run: |
        cd prometheus/documentation/prometheus-mixin
        jb install
        make prometheus_alerts.yaml
    - run: |
        git clone --depth 1 --no-checkout --filter=blob:none https://github.com/prometheus/node_exporter.git node_exporter
        cd node_exporter
        git checkout master -- docs/node-mixin
    - run: |
        cd node_exporter/docs/node-mixin
        jb install
        make node_alerts.yaml node_rules.yaml
    - run: |
        sudo mkdir /rules
        sudo cp -v prometheus/documentation/prometheus-mixin/*.yaml node_exporter/docs/node-mixin/*.yaml /rules/
        # cloudalchemy.ansible-prometheus expects rule files to have `.rules` extension
        for i in /rules/*.yaml; do sudo mv -v $i ${i%yaml}rules; done
    - run: ls -l /rules/
    - persist_to_workspace:
        root: /
        paths:
        - rules

  test:
    executor: python
    steps:
    - checkout
    - restore_cache:
        keys:
        - deps-{{ checksum "requirements.txt" }}
    - run: mkdir -p ~/.cache/pip
    - run: sudo pip install --cache-dir ~/.cache/pip -q -r requirements.txt
    - save_cache:
        key: deps-{{ checksum "requirements.txt" }}
        paths:
        - ~/.cache/pip
    - run: ansible-galaxy install -r roles/requirements.yml
    - run: ansible-playbook --syntax-check site.yml
    - run: ansible-lint site.yml
    - store_artifacts:
        path: test-reports
        destination: test-reports

  deploy:
    executor: python
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "46:a1:bb:55:6e:cd:3a:a5:2f:ea:13:46:ae:24:f0:19"
    - attach_workspace:
        at: .
    - run: cp -v go/bin/random playbooks/files/random
    - run: cp -rv rules playbooks/files/
    - restore_cache:
        keys:
        - deps-{{ checksum "requirements.txt" }}
    - run: sudo pip install --cache-dir ~/.cache/pip -q -r requirements.txt
    - deploy:
        name: Deploy to production
        command: ./deploy.sh

workflows:
  version: 2
  commit:
    jobs:
    - build
    - mixins
    - test
    - deploy:
        requires:
        - build
        - test
        filters:
          branches:
            only: master

  nightly:
    triggers:
    - schedule:
        cron: "0 14 * * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - build
    - mixins
    - test
    - deploy:
        requires:
        - build
        - test
        - mixins
